### ISSUE TITLE
Add Earth And Space Application

### ISSUE THREAD

**Issue by fnogatz** [Bengt/Awesome-DFKI#10]
See https://github.com/DFKI-Earth-And-Space-Applications. Maybe one of @hibanajjar998, @fmenat, @dinesh-k-natarajan, @mstricker13, @marnu35 could add their group's information?

**Comment by marnu35** [comment]
Yes this github can be added as the DFKI - Earth and Space Applications Team

**Comment by fnogatz** [comment]
Do you mind opening a pull request? :innocent:

**Comment by marnu35** [comment]
I am not a member of DFKI group on github, so I think I can not?

**Comment by fnogatz** [comment]
You could simply create a fork in your personal namespace.

**Comment by fnogatz** [comment]
Resolved via https://github.com/DFKI/Awesome-DFKI/pull/11.
